logging:
  config: classpath:logback.xml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kotlin-setting
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres